### ISSUE TITLE
Tinker, ensure plots render correctly

### ISSUE THREAD

**Issue by eroten** [Metropolitan-Council/ghg-cprg#29]
- [ ] interpretive alt text for all plots, including data source
  - [ ] 3 sentences: 1 descriptive, 1 interpretive, 1 broader point or contextual information
- [x] figure captions in consistent place
- [ ] plot titles descriptive and interpretive
- [ ] data source within plotly caption
- [x] set of PNG plotly plots without headings
- [ ] consistent colors
- [ ] group propane and kerosene into liquid stationary fuels
