### ISSUE TITLE
2018 inventory review

### ISSUE THREAD

**Issue by mcnamx** [Metropolitan-Council/ghg-cprg#38]
- [x] pull csvs from Tableau workbooks
- [x] check csvs for contents
- [x] review ghg.inv.app repository for other data
- [ ] cross-check with current CD_Emissions db contents
- [ ] reformat existing data for database where needed
- [ ] import existing 2018 data to CD_Emissions db
